### ISSUE TITLE
similtaneous ending of all studies

### ISSUE THREAD

**Issue by gregglind** [mozilla/heatmap#10]
solutions:
1.  most robust:  have a update addon at AMO, that self-uninstalls
2.  have some secondary overriding thing in the addon
3.  mess with prefs.firstrun

**Comment by gregglind** [comment]
or remove product requirement for simultaneous death :)

**Comment by crankycoder** [comment]
I've added a hard 90 day study end date ,and a date check on uninstall before trying to delete data.  This should be better as I'm not modifying the study duration anymore and the first run date is not modified any longer.
