### ISSUE TITLE
daydiff date is going to do the wrong thing

### ISSUE THREAD

**Issue by gregglind** [mozilla/heatmap#11]
' duration: daydiff(STUDY_END_DATE, new Date()),   // in days,'

the way this actaully works:
- during install simple_prefs.firstrun is set as date.now()
- every other time it will check is days(now() - firstrun) > DAYS

see #10

You could have a 2nd timer that checks time and expires it.

This all scares me a bit as hard to test, and expiry is a common source of issues.

**Comment by crankycoder** [comment]
I've removed the daydiff entirely now and just set a fixed 90 day cut off.  When the addon starts, it will check the date before trying to uninstall itself or continue with 'the usual' behaviour.
