### ISSUE TITLE
Session durations are really short

### ISSUE THREAD

**Issue by hannosch** [mozilla/heatmap#22]
Looking at the data from the first days, the session durations we get are really short.

95% are 1s or less
80% are 100ms or less
50% are 10ms or less

Especially 80% at 100ms or less is dubious. Humans take longer than 100ms to take in any visual input and react to it.

I'm not sure what is going on here. Either the timing events we take aren't quite right (DOM ready vs. page fully loaded vs. first paint?) or we might also get events for pages which are getting closed automatically.

**Comment by crankycoder** [comment]
I screwed up the nanosecond and millisecond conventions.

Duration should be fixed in 5e9ff0ad9e594038cac8b60b15bcb44337273d72
